### ISSUE TITLE
Menu button: wrong up arrow behavior

### ISSUE THREAD

**Issue by EthanJStark** [neezer/react-a11y-menu#4]
As described by [W3](https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-actions.html), 

* Menu button
  * <kbd>↑ </kbd>
    * Opens menu and moves focus to **last** menuitem

**Current behavior:**
Opens menu and moves focus to **first** menuitem

**Comment by jgbenito7** [comment]
We might just not be reseting the selected index on close

**Comment by jgbenito7** [comment]
> We might just not be reseting the selected index on close

Yeah that's what it is
