### ISSUE TITLE
Menu item: wrong Enter behavior

### ISSUE THREAD

**Issue by EthanJStark** [neezer/react-a11y-menu#5]
As described by [W3](https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-actions.html), 

* Menu (* this is an _open menu_)
  * <kbd>Enter </kbd>
    * Activates the menu item, causing the "Last Action" textbox to be updated.
    * Closes the menu.
    * Sets focus on the menu button

Can't speak to the "Last Action" business, but I do know that the above behavior should allow us to toggle the menu open and closed with the enter button, _without_ having the effect of clicking a link. You can try out this behavior on their example menu.

**Current behavior:**
* For an open menu, <kbd>Enter </kbd> has the effect of clicking a link.

**Comment by jgbenito7** [comment]
> For an open menu, Enter  has the effect of clicking a link.

this is probably a bad example for testing this behavior:

> Closes the menu.
> Sets focus on the menu button

But clicking enter on a link should follow the link, in other words:

> Activates the menu item

**Comment by EthanJStark** [comment]
Ah, interesting @jgbenito7  I think I misunderstood their example menu in creating this issue.

This is probably restating what you're saying in your comment, but just to confirm:

On their example menu, we get the following behavior:

* <kbd>Enter</kbd> opens a closed menu, and focuses on the first item
* <kbd>Enter</kbd> on an open menu does the following:
  * Closes the menu `~`
  * Sets focus on the menu button `~`
  * Activates the menu item

I think I was thrown off because "activates", in our menu use case, === "clicking a link to go to a new page", so the items marked with `~` aren't particularly relevant or visible.

If I have all of this right, go ahead and close this issue.

**Comment by neezer** [comment]
@jgbenito7 described the correct behavior: <kbd>Enter</kbd> on a menu item is the equivalent to clicking on that menu item.
